export const AcademicDeptPrograms: Record<string, string[]> = {
    'Architecture and Planning': [
        'Bachelor of Architecture (B.Arch.)',
        'Master of Planning (Urban Planning) (M.Plan.)',
        'Ph.D.',
    ],
    'Bioscience and Engineering': [
        'B.Tech Biotechnology',
        'M.Tech Bioengineering',
        'Ph.D.',
    ],
    'Chemical Engineering': [
        'B.Tech Chemical Engineering',
        'M.Tech Chemical Engineering',
        'Ph.D.',
    ],
    Chemistry: ['M.Sc. Chemistry', 'Ph.D.'],
    'Civil Engineering': [
        'B.Tech Civil Engineering',
        'M.Tech Environmental Engineering',
        'M.Tech Water Resources Engineering',
        'M.Tech Offshore Structures',
        'M.Tech Geotechnical Engineering',
        'M.Tech Traffic and Transportation Planning',
        'M.Tech Structural Engineering',
        'Ph.D.',
    ],
    'Computer Science & Engineering': [
        'B.Tech Computer Science & Engineering',
        'M.Tech Computer Science & Engineering',
        'M.Tech Computer Science & Engineering (Artificial Intelligence & Data Analytics)',
        'M.Tech Computer Science & Engineering (Information Security)',
        'Ph.D.',
    ],
    'Department of Education': [
        '4-year Integrated Teacher Education Programme (ITEP) B.Sc-B.Ed.',
        'Ph.D.',
    ],
    'Electrical Engineering': [
        'B.Tech Electrical & Electronics Engineering',
        'M.Tech Electric Vehicle Engineering',
        'M.Tech High Voltage Engineering',
        'M.Tech Industrial Power & Automation',
        'M.Tech Power Electronics',
        'M.Tech Power Systems',
        'M.Tech Instrumentation & Control Systems',
        'Ph.D.',
    ],
    'Electronics & Communication Engineering': [
        'B.Tech Electronics & Communication Engineering',
        'M.Tech Telecommunication',
        'M.Tech Signal Processing',
        'M.Tech Microelectronics & VLSI Design',
        'M.Tech Electronics Design & Technology',
        'Ph.D.',
    ],
    'Humanities, Arts and Social Sciences': ['Ph.D.'],
    'Materials Science and Engineering': [
        'B.Tech Materials Science & Engineering',
        'M.Tech Nanotechnology',
        'M.Tech Materials Science & Technology',
        'Ph.D.',
    ],
    Mathematics: ['M.Sc. Mathematics', 'Ph.D.'],
    'Management Studies': ['Master of Business Administration (MBA)', 'Ph.D.'],
    'Mechanical Engineering': [
        'B.Tech Mechanical Engineering',
        'M.Tech Thermal Sciences',
        'M.Tech Manufacturing Technology',
        'M.Tech Machine Design',
        'M.Tech Industrial Engineering & Management',
        'M.Tech Energy Engineering & Management',
        'Ph.D.',
    ],
    Physics: ['M.Sc. Physics', 'Ph.D.'],
};

export const DEPARTMENTS = {
    academic: [
        'Architecture and Planning',
        'Bioscience and Engineering',
        'Chemical Engineering',
        'Chemistry',
        'Civil Engineering',
        'Computer Science & Engineering',
        'Department of Education',
        'Electrical Engineering',
        'Electronics & Communication Engineering',
        'Humanities, Arts and Social Sciences',
        'Materials Science and Engineering',
        'Mathematics',
        'Management Studies',
        'Mechanical Engineering',
        'Physics',
    ],
    nonAcademic: [
        'Library',
        'Hostel Administration',
        'Accounts and Finance Department',
        'Training and Placement Cell',
        'Sports and Physical Education Department',
        'IT Services / Computer Centre',
        'Transport Department',
    ],
};
